# Form implementation generated from reading ui file 'donload_y.ui'
#
# Created by: PyQt6 UI code generator 6.2.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(664, 448)
        font = QtGui.QFont()
        font.setPointSize(9)
        MainWindow.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("Фото/ikonka-video-s-youtube-na-android-telefon.jpg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("QWidget{\n"
"    background-color: #808080;\n"
"}\n"
"QGroupBox{\n"
"    background-color: #A9A9A9;\n"
"    color: #00008B;\n"
"    border: 1px solid #00FA9A;\n"
"}\n"
"QLabel{\n"
"    background-color: #A9A9A9;\n"
"    color: #8B0000;\n"
"}\n"
"QLineEdit{\n"
"    background-color: #C0C0C0;\n"
"    color: #00008B;\n"
"    border: 1px solid #FFD700;\n"
"}\n"
"QLineEdit:focus{\n"
"    border: 2px dashed #9400D3;\n"
"}\n"
"QPushButton{\n"
"    background-color: black;\n"
"    color: yellow;\n"
"    border: 1px solid #FF8C00;\n"
"}\n"
"QPushButton:hover{\n"
"    border: 2px dashed #ADFF2F;\n"
"}\n"
"QPushButton:pressed{\n"
"    background-color: #ADFF2F;\n"
"    color: black;\n"
"    border: 1px solid black;\n"
"}\n"
"QPushButton:disabled{\n"
"    background-color: #C0C0C0;\n"
"    color: black;\n"
"    border: none;\n"
"}\n"
"QProgressBar{\n"
"    border: 1px solid #0000CD;\n"
"    color: yellow;\n"
"    text-align: center;\n"
"}\n"
"QProgressBar:chunk{\n"
"    width: 6px;\n"
"    margin: 5px;\n"
"}\n"
"QRadioButton{\n"
"    background-color: #A9A9A9;\n"
"    color: #8B0000;\n"
"}\n"
"QRadioButton:hover{\n"
"    color: #000080;\n"
"    border: 2px dashed #ADFF2F;\n"
"}\n"
"QRadioButton:pressed{\n"
"    background-color: #ADFF2F;\n"
"    color: black;\n"
"    border: 1px solid black;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton_exit = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_exit.setGeometry(QtCore.QRect(550, 410, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pushButton_exit.setFont(font)
        self.pushButton_exit.setObjectName("pushButton_exit")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 491, 141))
        self.groupBox.setObjectName("groupBox")
        self.pushButton_FAQ_put = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_FAQ_put.setGeometry(QtCore.QRect(450, 60, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_FAQ_put.setFont(font)
        self.pushButton_FAQ_put.setObjectName("pushButton_FAQ_put")
        self.pushButton_FAQ_link = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_FAQ_link.setGeometry(QtCore.QRect(450, 20, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_FAQ_link.setFont(font)
        self.pushButton_FAQ_link.setObjectName("pushButton_FAQ_link")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(10, 20, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setWordWrap(True)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(10, 60, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_2.setWordWrap(True)
        self.label_2.setObjectName("label_2")
        self.lineEdit_link = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_link.setGeometry(QtCore.QRect(140, 20, 261, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_link.setFont(font)
        self.lineEdit_link.setObjectName("lineEdit_link")
        self.lineEdit_put = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_put.setGeometry(QtCore.QRect(140, 60, 261, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_put.setFont(font)
        self.lineEdit_put.setObjectName("lineEdit_put")
        self.pushButton_clear = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_clear.setGeometry(QtCore.QRect(10, 100, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pushButton_clear.setFont(font)
        self.pushButton_clear.setObjectName("pushButton_clear")
        self.pushButton_path_folder = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_path_folder.setGeometry(QtCore.QRect(410, 60, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_path_folder.setFont(font)
        self.pushButton_path_folder.setObjectName("pushButton_path_folder")
        self.pushButton_info_in_file = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_info_in_file.setEnabled(True)
        self.pushButton_info_in_file.setGeometry(QtCore.QRect(350, 100, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pushButton_info_in_file.setFont(font)
        self.pushButton_info_in_file.setObjectName("pushButton_info_in_file")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 320, 491, 121))
        self.groupBox_2.setObjectName("groupBox_2")
        self.progressBar = QtWidgets.QProgressBar(self.groupBox_2)
        self.progressBar.setGeometry(QtCore.QRect(190, 20, 261, 41))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.progressBar.setFont(font)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.label_progress = QtWidgets.QLabel(self.groupBox_2)
        self.label_progress.setGeometry(QtCore.QRect(10, 20, 171, 41))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_progress.setFont(font)
        self.label_progress.setText("")
        self.label_progress.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_progress.setWordWrap(True)
        self.label_progress.setObjectName("label_progress")
        self.label_progress_2 = QtWidgets.QLabel(self.groupBox_2)
        self.label_progress_2.setGeometry(QtCore.QRect(120, 70, 261, 41))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_progress_2.setFont(font)
        self.label_progress_2.setText("")
        self.label_progress_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_progress_2.setWordWrap(True)
        self.label_progress_2.setObjectName("label_progress_2")
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setGeometry(QtCore.QRect(510, 10, 151, 101))
        self.groupBox_3.setObjectName("groupBox_3")
        self.radioButton = QtWidgets.QRadioButton(self.groupBox_3)
        self.radioButton.setGeometry(QtCore.QRect(10, 20, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.radioButton.setFont(font)
        self.radioButton.setChecked(True)
        self.radioButton.setObjectName("radioButton")
        self.radioButton_2 = QtWidgets.QRadioButton(self.groupBox_3)
        self.radioButton_2.setGeometry(QtCore.QRect(10, 60, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.radioButton_2.setFont(font)
        self.radioButton_2.setObjectName("radioButton_2")
        self.groupBox_4 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_4.setGeometry(QtCore.QRect(10, 160, 491, 151))
        self.groupBox_4.setObjectName("groupBox_4")
        self.label_3 = QtWidgets.QLabel(self.groupBox_4)
        self.label_3.setGeometry(QtCore.QRect(10, 20, 51, 41))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_3.setWordWrap(True)
        self.label_3.setObjectName("label_3")
        self.label_title = QtWidgets.QLabel(self.groupBox_4)
        self.label_title.setGeometry(QtCore.QRect(90, 20, 391, 41))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_title.setFont(font)
        self.label_title.setStyleSheet("color: black;")
        self.label_title.setText("")
        self.label_title.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_title.setWordWrap(True)
        self.label_title.setObjectName("label_title")
        self.label_5 = QtWidgets.QLabel(self.groupBox_4)
        self.label_5.setGeometry(QtCore.QRect(10, 70, 111, 41))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_5.setWordWrap(True)
        self.label_5.setObjectName("label_5")
        self.label_time = QtWidgets.QLabel(self.groupBox_4)
        self.label_time.setGeometry(QtCore.QRect(190, 80, 121, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_time.setFont(font)
        self.label_time.setStyleSheet("color: black;")
        self.label_time.setText("")
        self.label_time.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_time.setWordWrap(True)
        self.label_time.setObjectName("label_time")
        self.pushButton_download = QtWidgets.QPushButton(self.groupBox_4)
        self.pushButton_download.setEnabled(True)
        self.pushButton_download.setGeometry(QtCore.QRect(370, 110, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pushButton_download.setFont(font)
        self.pushButton_download.setObjectName("pushButton_download")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.pushButton_clear.clicked.connect(self.lineEdit_link.clear) # type: ignore
        self.pushButton_clear.clicked.connect(self.lineEdit_put.clear) # type: ignore
        self.radioButton.toggled['bool'].connect(self.label_progress_2.clear) # type: ignore
        self.radioButton.toggled['bool'].connect(self.label_progress.clear) # type: ignore
        self.radioButton_2.toggled['bool'].connect(self.label_progress_2.clear) # type: ignore
        self.radioButton_2.toggled['bool'].connect(self.label_progress.clear) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Download video and audio from Youtube"))
        self.pushButton_exit.setText(_translate("MainWindow", "Вийти"))
        self.groupBox.setTitle(_translate("MainWindow", "Введення даних"))
        self.pushButton_FAQ_put.setText(_translate("MainWindow", "?"))
        self.pushButton_FAQ_link.setText(_translate("MainWindow", "?"))
        self.label.setText(_translate("MainWindow", "Посилання на відео"))
        self.label_2.setText(_translate("MainWindow", "Шлях куди скачати"))
        self.lineEdit_link.setPlaceholderText(_translate("MainWindow", "Посилання"))
        self.lineEdit_put.setPlaceholderText(_translate("MainWindow", "Шлях"))
        self.pushButton_clear.setText(_translate("MainWindow", "Очистити поля"))
        self.pushButton_path_folder.setText(_translate("MainWindow", "..."))
        self.pushButton_info_in_file.setText(_translate("MainWindow", "Інформація про файл"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Інформація про скачування"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Вибір формату"))
        self.radioButton.setText(_translate("MainWindow", "Завантажити відео"))
        self.radioButton_2.setText(_translate("MainWindow", "Завантажити аудіо"))
        self.groupBox_4.setTitle(_translate("MainWindow", "Інформація про файл"))
        self.label_3.setText(_translate("MainWindow", "Назва"))
        self.label_5.setText(_translate("MainWindow", "Тривалість відео"))
        self.pushButton_download.setText(_translate("MainWindow", "Завантажити"))